service: poc

provider:
  name: aws
  runtime: go1.x
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true # optional, enables tracing for all functions (can be true (true equals 'Active') 'Active' or 'PassThrough')

functions:
  shopifywebhook:
    handler: bin/lambda/shopifywebhook # required, handler set in AWS Lambda
    events:
      - httpApi:
          path: /webhook
          method: POST

    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sns:Publish
        Resource: "*"

  toairtable:
    handler: bin/lambda/toairtable # required, handler set in AWS Lambda
    events:
      - httpApi:
          path: /airtable
          method: POST
      - sns:
          topicName: shopify
          displayName: shopify



plugins:
  - serverless-iam-roles-per-function
